loki:
  enabled: true



dependencies:
- name: "loki"
  condition: loki.enabled
  repository: "file://../loki"
  version: "^0.30.0"
- name: "promtail"
  condition: promtail.enabled
  repository: "file://../promtail"
  version: "^0.23.0"
- name: "fluent-bit"
  condition: fluent-bit.enabled
  repository: "file://../fluent-bit"
  version: "^0.1.0"
- name: "grafana"
  condition: grafana.enabled
  version: "~3.8.15"
  repository:  "https://kubernetes-charts.storage.googleapis.com/"
- name: "prometheus"
  condition: prometheus.enabled
  version: "~9.3.0"
  repository:  "https://kubernetes-charts.storage.googleapis.com/"
- name: "filebeat"
  condition: filebeat.enabled
  version: "~7.8.0"
  repository:  "https://helm.elastic.co"
- name: "logstash"
  condition: logstash.enabled
  version: "~2.4.0"
  repository:  "https://kubernetes-charts.storage.googleapis.com/"

promtail:
  enabled: true

fluent-bit:
  enabled: false

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 6.7.0

prometheus:
  enabled: false

filebeat:
  enabled: false
  filebeatConfig:
    filebeat.yml: |
      # logging.level: debug
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
      output.logstash:
        hosts: ["logstash-loki:5044"]

logstash:
  enabled: false
  image:
    repository: grafana/logstash-output-loki
    tag: 1.0.1
  filters:
    main: |-
      filter {
        if [kubernetes] {
          mutate {
            add_field => {
              "container_name" => "%{[kubernetes][container][name]}"
              "namespace" => "%{[kubernetes][namespace]}"
              "pod" => "%{[kubernetes][pod][name]}"
            }
            replace => { "host" => "%{[kubernetes][node][name]}"}
          }
        }
        mutate {
          remove_field => ["tags"]
        }
      }
  outputs:
    main: |-
      output {
        loki {
          url => "http://loki:3100/loki/api/v1/push"
          #username => "test"
          #password => "test"
        }
        # stdout { codec => rubydebug }
      }
