repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:

  - name: simpleapp
    namespace: dev
    chart: ./charts/simpleapp
    values:
    - "./charts/simpleapp/values.yaml"

  - name: loki
    namespace: monitoring
    chart: ./charts/loki/loki-stack
    values:
     - "./charts/loki/loki-stack/values.yaml"

  # - name: grafana
  #   namespace: monitoring
  #   chart: ./charts/grafana
  #   values:
  #    - "./charts/grafana/values.yaml"
